springdoc:
  swagger-ui:
    tags-sorter: "alpha"   # 스웨거 UI 알파벳순. 5.29 정
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
      default-encoding: UTF-8


  jpa:
    hibernate:
      ddl-auto: update  # or validate, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token:
    header: Authorization
    expiration-time: 900 #60 * 15 (15분)
  refresh-token:
    header: Authorization_refresh
    expiration-time: 604800 #60 * 60 * 24 * 7 (7일)
