name: 개발환경 배포 CICD

# main 브랜치에 Push 이벤트 발생시 동작.
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      PORT: ${{ secrets.PORT }}
      MYSQL_URL: ${{ secrets.MYSQL_URL }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gradlew authority 변경
        run: chmod +x ./gradlew

      - name: Spring Boot 빌드
        run: |
          ./gradlew clean build --exclude-task test

      - name: 도커 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}

      - name: docker image 빌드 및 push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_DEV_USERNAME }}/point-career:latest .
          docker push ${{ secrets.DOCKERHUB_DEV_USERNAME }}/point-career:latest

      - name: configure aws credentials 접근 권한 취득
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ACCESS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: AWS SSH into EC2 & Docker Dangling 이미지 prune & 이미지 pull & 명령어 실행
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_DEV_USERNAME }} -p ${{ secrets.DOCKERHUB_DEV_TOKEN }}
            sudo docker pull ${{ secrets.DOCKERHUB_DEV_USERNAME }}/point-career:latest
            sudo docker stop point-career
            sudo docker rm point-career
            sudo docker run -it -d -p 8080:8080 --name point-career ${{ secrets.DOCKERHUB_DEV_USERNAME }}/point-career:latest
            sudo docker image prune -f
